# asdf 
. "/usr/local/opt/asdf/libexec/asdf.sh"

# compinit
autoload -Uz compinit
compinit

### exports
export PATH="$HOME/.asdf/shims:$PATH"

export EDITOR=nvim
export ERL_AFLAGS="-kernel shell_history enabled"

# Remote
export AWS_PROFILE=sts

### aliases
alias ll='ls -l'

alias g="git"

alias f="mix format"
alias t="mix test"
alias tw="mix test.watch"

# Starship prompt
eval "$(starship init zsh)"

# tmp

export PATH="/usr/local/opt/libxml2/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/libxml2/lib"
export CPPFLAGS="-I/usr/local/opt/libxml2/include"
export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"

export LDFLAGS="-L/usr/local/opt/libxslt/lib"
export CPPFLAGS="-I/usr/local/opt/libxslt/include"
export PKG_CONFIG_PATH="/usr/local/opt/libxslt/lib/pkgconfig"

export LDFLAGS="-L/usr/local/opt/openssl@1.0/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.0/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.0/lib/pkgconfig"
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
