#  asdf 
. /opt/homebrew/opt/asdf/libexec/asdf.sh

## postgres
export LDFLAGS="-L$(brew --prefix icu4c)/lib -L$(brew --prefix openssl)/lib"
export CPPFLAGS="-I$(brew --prefix icu4c)/include -I$(brew --prefix openssl)/include"
export PKG_CONFIG_PATH="$(brew --prefix icu4c)/lib/pkgconfig:$(brew --prefix openssl)/lib/pkgconfig"

# compinit
autoload -Uz compinit
compinit

### exports
export PATH="$HOME/.asdf/shims:$PATH"

export EDITOR=nvim
export ERL_AFLAGS="-kernel shell_history enabled"

### aliases
alias nv="nvim"

alias ll='ls -l'

alias g="git"

alias f="mix format"
alias t="mix test"
alias tw="mix test.watch"

# Starship prompt
eval "$(starship init zsh)"
PATH=/Users/mickey/.asdf/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/iTerm.app/Contents/Resources/utilities:/opt/homebrew/opt/libpq/bin

# Remote
export AWS_PROFILE=sts

compdef remotectl
compdef _remotectl remotectl
source <(remotectl completion zsh)

export PATH="$PATH:/Users/mickey/.asdf/installs/python/3.12.5/bin"

# Added by Windsurf
export PATH="/Users/mickey/.codeium/windsurf/bin:$PATH"

# Jinn
export LINE_CLIENT_ID=2007208601
export LINE_CLIENT_SECRET=0b5f91726b883b60131a040600cc5a50

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

LIVEBOOK_SECRET_KEY_BASE=9apaSK16bPaF8XKzhyfYcWPaZCbGQ0K7qgNLGsINZ0Qv8kJNCHr94bSWx9+pA2JD
